spring:
  application:
    name: movieflix

  datasource:
    url: jdbc:postgresql://localhost5432/movieflix
    username: postgres
    password: 75783598
    driver-class-name: org.postgresql.Driver

  jpa:
   database-platform: org.hibernate.dialect.PostgreSQLDialect
   show-sql: true

  flyway:
    enabled: true
